language: python
python: '3.9'
node_js: 10.16.3
before_install:
- npm install dredd@14.0.0 --global
- pipenv install --dev
script:
- dredd oas.yaml http://127.0.0.1:8000 --hookfiles=./hooks.py --language=python --server
  "uvicorn app.app:app"
deploy:
  provider: heroku
  api_key:
    secure: gzVe0NpeGzvjtttGf8pNaYF8rGpdtZby2OnqtvGQwkvNrijYxg4UWY/xizVKosHUBaS8GNKrziyiq414Dy9eMccKsgv1wjbyJwYyJn5s66DSnEZ8sc98P1mn1kfo2B6/unMINUx/adTnKI5zn1A9+Pjo1xOSAXPvToXAiDJsg/REjNDIisCOYy7gtBsb3a8Vv87Q1jzd7QmUnPorHDvWybU4/u7aDCEnogoHsk23FHvmFtT33TLrEtuiTbPnyL8UzsfamIeyLGLNTRUcnwWWjwVe8GTDNYX73/plSLQZJho3enZ25O3Fg6kZn1767ie6jTojBRWGSytaTH11ZqZOTzQSGnUGKQz2hOiPiAm2P5txAOIcW+yN6XvbsHryOHhnb5gCOFAgKddXmXXZHauI7RNfOsj3N9rqPs/taNiadZi11ihHYgh4l6U6w3alU58ylz+nFfXDKZaTFrDnrudYHXfVDFVRXqv8zzp9UF+SdnQovu5RLJZTmyIj+QBMe2UT7kgZXYDtKlQ0bh4BtUj40p8RokxZ/zvUIgX62rsaGzKoJnd5+iDO5hE1oYKYMa1lVV0wVRrHeL/bzDNj+3/1Uk7c1KCKP6QtoJBsjpFv63LADKqiRXjLbBpz/xf6Hqg32aZtsvbOjyFU70/OgtSs4RAJdsbK/JOV7eNFAqXhV0U=
  app:
    master: conf42-python-2021
