language: python
python: '3.9'
node_js: 10.16.3
before_install:
- npm install dredd@14.0.0 --global
- pipenv install --dev
script:
- dredd oas.yaml http://127.0.0.1:8000 --hookfiles=./hooks.py --language=python --server
  "uvicorn app.app:app"
deploy:
  provider: heroku
  api_key:
    secure: TDoCu1DN66kqBqrnhcLkLR61oL5itjrZ4uZBBNdRw/xfMaedNJNYLqZ0pqrfSqO+rLp0KkNdfiLl9JRXzOE9+KE0KbB4dfqLcZLsd5kSYgk8OJYhrrqy9gEG1ud5ISfgSuS6T7o+OpdFHN7f8yIKKcmTryVaAJfGn6A0axwgs/8q3ehQGPdsJW0uObqB0T3f1QLnwnFXU6J56RcBowS4YWKnFI3K6vJe21ec1YRKyFtpYX69qd6ySiDJbO/nAVhONFnRMr31oA4zFwML1hDUIEvFGp80in4mfiCO1k4mnNyuaAMaUkFn8tRGF6IHCHjRIn+TrT9A2s+NdNvbrX7cm5XMp3zso2Ed0Ee2aAcq7OlSHwppqZiQbdS9dA4ghOduWsqWolfMlm84tWHi8FY+QSj0HaawyhSEo6vMV7QwjYJ3YXMgyUAvEQhLhb8oCOxAkHJu59oSi1SpLuYqb6onR2ZjbNQ1Ksv9MEIduoXiMzx+U9KPgOrqdxOEib4/IE/6PApSu/CZRjUR+v8R0I157h+hqU/4dcil3qmxicL5wS1VQ+UDjxHQ2bxIrCN8WwyrYukxHgOpU304VFiWcXUnfpKG/QiQagusw+j8vz4CsbVR8LIOkpdCjjRpY2LO0k3B0+aQgwlWZAk52/YenvstejxBq00PiWpIRFswRK0zoQ8=
  app:
    master: conf42-python-2021
